# .github/FUNDING.yml

github: [thesoungali]   # Ton pseudo GitHub
patreon: thesoungali
open_collective: thesoungali
ko_fi: thesoungali
liberapay: thesoungali
issuehunt: thesoungali
buy_me_a_coffee: thesoungali
thanks_dev: thesoungali
custom: ['https://thesoungali.com/sponsor', 'https://paypal.me/thesoungali']
